dist: xenial
sudo: false
language: python
python:
- 3.6
- 3.7
- 3.8
before_install:
- pip install --upgrade setuptools
install:
- pip install nox
- pip install .
script:
- nox
deploy:
  provider: pypi
  user: chezou
  password: $PYPI_PASSWORD
  distributions: sdist bdist_wheel
  on:
    tags: true
    python: 3.7
